#!/usr/bin/env bash
#This is a loop that does nothing!

for (( i=1; i<=100; i++ ))
do
a=$((i%3))
b=$((i%5))
    if [ "$a" -eq "0" ] && [ "$b" -eq "0" ]
    then
        echo "FizzBuzz"
    elif [ "$a" -eq "0" ]
    then
        echo "Fizz"
    elif [ "$b" -eq "0" ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
