#!/usr/bin/env bash
#This is a loop that does nothing!

i=1

while [ "$i" -le "20" ]
do
    echo "$i"
    i=$((i+1))
    if [ "$i" -eq "4" ]
    then
        echo "bad luck form China"
    elif [ "$i" -eq "9" ]
    then
        echo "good luck from Japan"
    elif [ "$i" -eq "17" ]
    then
        echo "good luck from Italy"
    fi
done
