#!/usr/bin/env bash
#This is a loop that does nothing!

i=1

while [ "$i" -le "20" ]
do
    echo "$i"
    i=$((i+1))
    
    case $i in

    4)
        echo "bad luck for China"
    ;;

    9)
        echo "bad luck for Japan"
    ;;

    17)
        echo "bad luck for Italy"
    ;;

    esac

done
